### ISSUE TITLE
bug in modal

### ISSUE THREAD

**Issue by mousavi-sh** [AliRoostae/Blazor_PersianDatePickerZO#2]
hello
date picker on modal dialog has error.
please check it
tanks

**Comment by AliRoostae** [comment]
سلام .  ممنون از گزارش شما .  
حقیقت من درست متوجه نشدم منظور شما کدام قسمت هست و چه خطای بهتون میده . ممنون میشم  پیام خطا را اینجا بزارید و کمی بیشتر توضیح بدید  تا بررسی کنم

**Comment by MousaviSaman** [comment]
این رفع شده است . متشکر
