### ISSUE TITLE
بسته شدن پنجره انتخاب

### ISSUE THREAD

**Issue by MousaviSaman** [AliRoostae/Blazor_PersianDatePickerZO#3]
سلام و تشکر 
اگر بخواهم با انتخاب تاریخ و بدون کلیک بر روی گزینه تایید ، پنجره انتخاب بسته شود چه تغییری باید بدهم؟

**Comment by AliRoostae** [comment]
سلام 
اضافه کردم . به نظرم اینطور بهتر شد .
[        public  EventCallback Close { get; set; } ](https://github.com/AliRoostae/Blazor_PersianDatePickerZO/blob/3cbc043c0f5c24a8a637cd515cdaf11a12818ef9/Lib/Component/DayZO.razor.cs#L10)

**Comment by MousaviSaman** [comment]
عالی
تشکر
