### ISSUE TITLE
close popup auto.

### ISSUE THREAD

**Issue by MousaviSaman** [AliRoostae/Blazor_PersianDatePickerZO#4]
سلام مهندس .
ممنون بابت این کامپوننت زیبا و توجه شما به درخواست ها 
آیا امکانش هست تغییری بدید که با کلیک بر روی محیط خارج از Input  ، پنجره انتخاب تاریخ بسته شود
ممنون

**Comment by AliRoostae** [comment]
سلام . شرمنده اگر دیر جواب میدم . کمی درگیر هستم این چند وقت . 
خوشحالم که از این کامپوننت  تونسته کمی به شما کمک کنه .   حقیقت فعلا نمی تونم تا چند وقت برم سراغ  این پروژه  .
ولی کمی راهنمایی میکنم  خودت انجام بدی  ممنون میشم برای منهم بفرستی . 
برای این کار شما باید جاوا اسکریپت بنویسی . من سعی کردم تو این پروژه جاوا اسکریپت ننویسم 
این لینک را مطالعه کن   
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-5.0  

شما نیاز داری که ایونت را از طریق جاوا ارسال کنی . و وقتی موس خارج از محدوده بود یک ایونت بفرستی و   تو کلاس   ZeroOneDatePicker    تابع  ColsePopup    را فراخوانی کنی   

تو جاوا اسکریپت این تابع  باید کارت را راه بندازه  چک کن   

```
  document.addEventListener("click", function(event) {
        var divElement = document.querySelector(".OutsideDiv");  
        if (divElement && !divElement.contains(event.target)) {
            // موس خارج از دیو است
            // اینجا می‌توانید تابع C# را فراخوانی کنید
            DotNet.invokeMethodAsync("MyAppNamespace", "HandleMouseClickOutside");
        }
    });
```

این قسمت  از کد  را هم  تغییر بده 
 ```
if (_show)
 {
     <div class="OutsideDiv frame-position-zo frame @ThemePickerZO">
.......}
```
https://github.com/AliRoostae/Blazor_PersianDatePickerZO/blob/3cbc043c0f5c24a8a637cd515cdaf11a12818ef9/Lib/Component/ZeroOneDatePicker.razor#L15

ودر Cs    همین کلاس     
```

public async Task HandleMouseClickOutside()
{
ColsePopup();
}

```
https://github.com/AliRoostae/Blazor_PersianDatePickerZO/blob/3cbc043c0f5c24a8a637cd515cdaf11a12818ef9/Lib/Component/ZeroOneDatePicker.razor.cs#L37

**Comment by MousaviSaman** [comment]
بسیار عالی. لطف کردی.
اگر جواب گرفتم ، می‌فرستم برات .
متشکر

**Comment by MousaviSaman** [comment]
AppDatePickerZeroOne.js:

window.outsideClickHandler = {
    addEvent: function (elementId, dotnetHelper) {
        window.addEventListener("click", (e) => {
            var el=document.getElementById(elementId)
            if (el && !el.contains(e.target)) {
                dotnetHelper.invokeMethodAsync("InvokeClickOutside");
            }
        });
    }
};


ZeroOneDatePicker.razor:

div class="frame-position-zo frame @ThemePickerZO" id="dateselector"

ZeroOneDatePicker.razor.cs:

  [Inject]
  IJSRuntime JSRuntime { get; set; }
protected override Task OnInitializedAsync()
{
    JSRuntime.InvokeAsync<object>("outsideClickHandler.addEvent", "dateselector", DotNetObjectReference.Create(this));
    return base.OnInitializedAsync();
}
[JSInvokable]
public void InvokeClickOutside()
{
    ColsePopup();
}

**Comment by AliRoostae** [comment]
سلام . آبدیت شد

https://github.com/AliRoostae/Blazor_PersianDatePickerZO/blob/511f7020cafdae1511e58db299ab15a9f01174b0/Lib/Component/DatePickerZO.razor.cs#L10C9-L48C1

**Comment by MousaviSaman** [comment]
سلام
بسیار عالی
