### ISSUE TITLE
چند تا نکته و بهبود

### ISSUE THREAD

**Issue by behroozbc** [AliRoostae/Blazor_PersianDatePickerZO#5]
سلام 
من خیلی کتابخونه اتون خوشم اومد به نظر خوب میاد
چندتا نکته در مورد میخواستم بگم 
۱. اگر امکانش هستش اسم گذاری تمام کامپوننت ها شبیه هم باشن نه به طور مثل کامپوننت سال ماه شبیه بقیه اصلا نیست
۲. اگر میشه دمو که داخل ریپوزیتوری هستش را روی گیتهاب پیجز بالا بیارید که راحت تر بشه دمو و یه برداشتی از کتاب خونه اتون پیدا کرد.
۳. در فایل readme نوشتید دات نت ۶ اما بهتره که اینو به روز کنید

**Comment by behroozbc** [comment]
اگر امکانش هستش یه کامپوننت برای این که روز ماه و سال رو بگیره بزارید.

**Comment by AliRoostae** [comment]
سلام.
خیلی وقت بود بهش سر نزده بودم . ممنون از پیشنهاداتون 
نام کامپوننتها را اصلاح کردم . 
در مورد پیچز   سوادم نمیرسه  سعی میکنم یادش بگیرم  .یکم دردسر داره فکر کنم برای این پروژه 

دات نت را هم 8 کردم
برای کامپوننت سال ماه روز هم  اگر  Format="yyyy/MM/DD"     استفاده کنید   ساعت را حذف کردم . توی سمپل هم نمونه را گذاشت 
            <DatePickerZO @bind-SelectDate="@_date" DateFa="DateFa" PopupDatePickerZO="true" Format="yyyy/MM/dd" />
https://github.com/AliRoostae/Blazor_PersianDatePickerZO/blob/511f7020cafdae1511e58db299ab15a9f01174b0/Sample_WebAssembly/Pages/Index.razor#L46

**Comment by behroozbc** [comment]
گیتهاب پیجز چیز خیلی عجیبی نیست 
تمام ریپوزتوری های پابلیک گیتهاب میتونن یه صفحه برای خودشون داشته باشن 
فک کنم این رو در بدترین حالت توی ۵۰ دقیقه بشه راه انداخت
بازم کارتون خیلی خوب بود
